name: Test Markdown Files
# This workflow lints Markdown files in the repository.
# It is triggered on pull requests and can also be run manually.

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'html-to-markdown-lint'
  push: # Add push trigger
    branches:
      - '**' # Match all branches

jobs:
  lint-markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          # Use the branch specified in workflow_dispatch input
          ref: ${{ github.event.inputs.branch }}
          
      - name: Check for config file
        run: cat .markdownlint.json
        run: ls -al

      - name: Lint Markdown files
        run: |
          npm install -g markdownlint-cli
          markdownlint --config .markdownlint.json "docs/**/*.md"

